### ISSUE TITLE
Implementar HTTP GET/plants

### ISSUE THREAD

**Issue by mdelapenya** [gdgtoledo/linneo#5]
Este endpoint retornará todas las plantas existentes en el almacenamiento primario, en este caso Elasticsearch

**Comment by mdelapenya** [comment]
Voy a comenzar con esta tarea: voy a crear una PR con la implementación en Go utilizando un framework web como [Gin-Gonic](https://gin-gonic.com/) o [Gobuffalo](https://gobuffalo.io/es/)

**Comment by mdelapenya** [comment]
Tras leer https://www.slant.co/versus/4797/20918/~gin-gonic_vs_buffalo, voy a tirar por Gin-Gonic

**Comment by javierlopezdeancos** [comment]
Voy a leereme ese artículo, me encanta empezar a implementar en Go

**Comment by javierlopezdeancos** [comment]
Exactamente podrías indicarnos aquí después de tu lectura y tu experiencia como backend porque, a tu criterio, es mejor Gin-gonic? he leído el artículo y tengo mis ideas pero quisiera contrastarlas con alguien con mas experiencia en go y en API.

**Comment by mdelapenya** [comment]
Pues me gusta más `Gin-gonic` porque parece más simple para implementar un API, sin necesitar un interfaz gráfico de usuario atado al framework, como hace GoBuffalo. Éste último proporciona todo lo necesario para montar el API y además proporciona un sistema de templates para poder crear las vistas. Por tanto es más pesado en cuanto a dependencias.

Desde mi punto de vista, nuestro scaffolding, donde GoBuffalo también tiene su generator, es tan simple en este momento que no necesita justamente esto: un generador de código boilerplate.

Otra cosa es lo que pasará en un futuro, pero a día de hoy es simple.

**Comment by mdelapenya** [comment]
Otro motivo de preferencia: `Gin` tiene integración con el APM Agent de Go de Elastic, así que sería posible meter trazas a la aplicación https://www.elastic.co/guide/en/apm/agent/go/current/supported-tech.html

SideNote: y me gusta que rime con `botellín`
